### ISSUE TITLE
Adaptation for embedded use

### ISSUE THREAD

**Issue by grosenberg** [antlr/codebuff#32]
In taking a prelim look at adapting CodeBuff for embedded use, the wide use of statics presents a question of what would be acceptable.  Proposal would be refactor the CodeBuff Tool to match the form of the Antlr4 Tool.  If there is an alternate preference, please describe and I will prepare a pull request accordingly.

**Comment by parrt** [comment]
Yeah, the statics are either debugging or related. Code is thread-safe to run multiple formats at same time. I hit that area of code hard.

**Comment by grosenberg** [comment]
Branched as CodeBuff2 in https://github.com/grosenberg/codebuff/tree/codebuff2

Removes the statics, refactors to a more conventional programming style, and configures the tool for embedded use. Works, but not well tested. More to do.

**Comment by parrt** [comment]
Thanks Gerald. I will take a look when I get back to codebuff. I want to integrate a version into my plugin so this could help quite a bit.

**Comment by grosenberg** [comment]
Closing in favor of Adept at https://github.com/grosenberg/adept
