### ISSUE TITLE
Add snippet with example code to README

### ISSUE THREAD

**Issue by JelteF** [antlr/codebuff#33]
This sounds very cool, but it would definitely be good to be able to see some example results right away.
Show some unformatted code and then the result after going to the program.

**Comment by parrt** [comment]
Hi. The input is completed squeezed of whitespace/newlines so only the output really matters. You can check out the [output](https://github.com/antlr/codebuff/tree/master/output) dir for leave-one-out formatting of the various [corpora](https://github.com/antlr/codebuff/tree/master/corpus). I still need to clean up the code to make an easily embeddable one.
