### ISSUE TITLE
retargetable pretty printer generator

### ISSUE THREAD

**Issue by dvc94ch** [antlr/codebuff#38]
Are there plans for making it retargetable like antlr?

**Comment by parrt** [comment]
it takes a grammar for whatever language so you're good to go.

**Comment by dvc94ch** [comment]
Pretty printers for file formats is a common task. For example a js backend would be useful for supporting it in various editors (theia, vscode, atom), or any kind of serialization.

**Comment by parrt** [comment]
Then all you need is a JavaScript grammar
