### ISSUE TITLE
Use your library

### ISSUE THREAD

**Issue by quantrpeter** [antlr/codebuff#41]
Hi
   My name is Peter, writing a antlr source code formatter is hard. So I want to use this project to format antlr source code in my netbeans-antlr plugin https://gitlab.com/mcheung63/netbeans-antlr . Is there a example i pass this lib a string of antlr grammer source and return me a string as a formatted source?
thanks
Peter

**Comment by parrt** [comment]
I thought we did that for the paper so must be around somewhere.
